[book]
authors = ["Pavel Perestoronin"]
language = "en"
multilingual = false
src = "book"
title = "My IoT"

[rust]
edition = "2018"

[build]
build-dir = "docs"
create-missing = false

[output.html]
curly-quotes = true
copy-fonts = true
google-analytics = "UA-65034198-8"
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/eigenein/my-iot-rs"

[output.linkcheck]
follow-web-links = false
traverse-parent-directories = false
warning-policy = "error"
