[package]
name = "my-iot"
description = "Yet another home automation"
version = "0.42.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
homepage = "https://github.com/eigenein/my-iot-rs"
documentation = "https://github.com/eigenein/my-iot-rs/wiki"
repository = "https://github.com/eigenein/my-iot-rs"
publish = true
readme = "README.md"
keywords = ["iot"]
categories = ["command-line-utilities"]
license = "MIT"

[badges]
is-it-maintained-issue-resolution = { repository = "eigenein/my-iot-rs" }
is-it-maintained-open-issues = { repository = "eigenein/my-iot-rs" }

[profile.release]
lto = "fat"
codegen-units = 1

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
reqwest = { version = "0.10", features = ["rustls-tls", "blocking", "gzip", "json"] }
rouille = "3.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eventsource = "0.4"
crossbeam-channel = "0.3"
toml = "0.5"
regex = "1"
simple_logger = "1.0"
structopt = "0.3"
rusqlite = { version = "0.20", features = ["bundled"] }
askama = "0.9"
rmp-serde = "0.14"
uom = { version = "0.26", features = ["use_serde", "autoconvert", "f64", "si", "std", "try-from"] }
dirs = "2.0"
itertools = "0.9"
rlua = "0.17"
lazy_static = "1"
spa = "0.2"
