[package]
name = "my-iot"
description = "Yet another home automation"
version = "0.2.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
documentation = "https://github.com/eigenein/my-iot-rs/wiki"
repository = "https://github.com/eigenein/my-iot-rs"
publish = false
readme = "README.md"
keywords = ["iot"]
license = "MIT"

[badges]
travis-ci = { repository = "eigenein/my-iot-rs" }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5.1", features = ["serde"] }
openssl = { version = "0.10" }
humansize = "1.1.0"
# CLI.
clap = "2.33.0"
# Web client, server and template engine.
reqwest = "0.9.18"
rouille = "3.0.0"
markup = "0.3.1"
# Persistence.
rusqlite = "0.18.0"
# Logging.
env_logger = "0.6.2"
pretty_env_logger = "0.3.0"
log = "0.4"
# Serialization.
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
