[package]
name = "my-iot"
description = "Yet another home automation"
version = "0.20.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
homepage = "https://github.com/eigenein/my-iot-rs"
documentation = "https://github.com/eigenein/my-iot-rs/wiki"
repository = "https://github.com/eigenein/my-iot-rs"
publish = true
readme = "README.md"
keywords = ["iot"]
categories = ["command-line-utilities"]
license = "MIT"

[badges]
is-it-maintained-issue-resolution = { repository = "eigenein/my-iot-rs" }
is-it-maintained-open-issues = { repository = "eigenein/my-iot-rs" }

[dependencies]
chrono = { version = "0.4.7", features = ["serde"] }
chrono-tz = { version = "0.5.1", features = ["serde"] }
clap = "2.33.0"
reqwest = "0.9.20"
rouille = "3.0.0"
markup = "0.3.1"
rusqlite = "0.18.0"
env_logger = "0.6.2"
pretty_env_logger = "0.3.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eventsource = "0.4.0"
failure = "0.1.5"
crossbeam-channel = "0.3.9"
bus = "2.2.2"
toml = "0.5.3"
