[package]
name = "my-iot"
description = "Yet another home automation"
version = "0.38.2"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
homepage = "https://github.com/eigenein/my-iot-rs"
documentation = "https://github.com/eigenein/my-iot-rs/wiki"
repository = "https://github.com/eigenein/my-iot-rs"
publish = true
readme = "README.md"
keywords = ["iot"]
categories = ["command-line-utilities"]
license = "MIT"

[badges]
is-it-maintained-issue-resolution = { repository = "eigenein/my-iot-rs" }
is-it-maintained-open-issues = { repository = "eigenein/my-iot-rs" }

[dependencies]
chrono = { version = "0.4.7", features = ["serde"] }
chrono-tz = { version = "0.5.1", features = ["serde"] }
reqwest = { version = "0.10.1", features = ["rustls-tls", "blocking", "gzip", "json"] }
rouille = "3.0.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eventsource = "0.4.0"
failure = "0.1.5"
crossbeam-channel = "0.3.9"
toml = "0.5.3"
regex = "1"
simple_logger = "1.0.1"
structopt = "0.3"
rusqlite = { version = "0.20.0", features = ["bundled"] }
askama = "0.8"
rmp-serde = "0.14.2"
uom = { version = "0.26.0", features = ["use_serde", "autoconvert", "f64", "si", "std", "try-from"] }
