[package]
name = "my-iot"
version = "0.1.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
documentation = "https://github.com/eigenein/my-iot-rs/wiki"
repository = "https://github.com/eigenein/my-iot-rs"
publish = false
readme = "README.md"
keywords = ["iot"]
license = "MIT"

[badges]
travis-ci = { repository = "eigenein/my-iot-rs" }

[dependencies]
chrono = "0.4"
openssl = { version = "0.10", features = ["vendored"] }
# CLI.
clap = "2.33.0"
# Web client, server and template engine.
reqwest = "0.9.18"
rouille = "3.0.0"
askama = { version = "0.8.0" }
typed-html = "0.2.1"
# Persistence.
rusqlite = "0.18.0"
# Logging.
pretty_env_logger = "0.3.0"
log = "0.4"
# Serialization.
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
