[package]
name = "my-iot"
version = "0.1.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
openssl = { version = "0.10", features = ["vendored"] }
# CLI.
clap = "2.33.0"
# Web client, server and template engine.
rouille = "3.0.0"
askama = { version = "0.8.0" }
# Persistence.
sqlite = "0.24.0"
# Logging.
pretty_env_logger = "0.3.0"
log = "0.4"
# Serialization.
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
