[package]
name = "my-iot"
description = "Yet another home automation"
version = "0.15.0"
authors = ["Pavel Perestoronin <eigenein@gmail.com>"]
edition = "2018"
homepage = "https://github.com/eigenein/my-iot-rs"
documentation = "https://eigenein.github.io/my-iot-rs/my_iot/"
repository = "https://github.com/eigenein/my-iot-rs"
publish = true
readme = "README.md"
keywords = ["iot"]
license = "MIT"

[badges]
travis-ci = { repository = "eigenein/my-iot-rs" }

[dependencies]
chrono = { version = "0.4.7", features = ["serde"] }
chrono-tz = { version = "0.5.1", features = ["serde"] }
openssl = { version = "0.10" }
clap = "2.33.0"
reqwest = "0.9.18"
rouille = "3.0.0"
markup = "0.3.1"
rusqlite = "0.18.0"
env_logger = "0.6.2"
pretty_env_logger = "0.3.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
eventsource = "0.3.0"
failure = "0.1.5"
multiqueue = "0.3.2"
