max_width = 120
# comment_width = 120
# imports_layout = "HorizontalVertical"
# merge_imports = true
# reorder_impl_items = true
# format_code_in_doc_comments = true
# trailing_comma = "Vertical"
# normalize_doc_attributes = true
