name: Check

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: APT
        run: sudo apt-get update && sudo apt-get install -y libsqlite3-dev

      - name: Rustup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install
        run: cargo install mdbook mdbook-linkcheck
        env:
          CARGO_TARGET_DIR=target

      - name: Check
        run: make check
