name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Cache arm-unknown-linux-gnueabihf
        uses: actions/cache@v1
        with:
          path: docker-arm-unknown-linux-gnueabihf.tar
          key: ${{ runner.os }}-docker
      - name: Restore cache for arm-unknown-linux-gnueabihf
        run: docker load --input image.tar
        continue-on-error: true
      - name: Build for Raspberry Pi Zero (W)
        run: make docker/build/arm-unknown-linux-gnueabihf
      - name: Save cache for arm-unknown-linux-gnueabihf
        run: docker save my-iot-rs/arm-unknown-linux-gnueabihf > docker-arm-unknown-linux-gnueabihf.tar
      - name: Release
        id: release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload for Raspberry Pi Zero (W)
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/arm-unknown-linux-gnueabihf/release/my-iot
          asset_name: my-iot-arm-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream
