name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: docker.tar
          key: docker.tar

      - name: Load Docker Backup
        run: docker load --input docker.tar
        continue-on-error: true
      - name: Build for Raspberry Pi 0/1
        run: make docker/build/arm-unknown-linux-gnueabihf
      - name: Build for Raspberry Pi 2/3/4
        run: make docker/build/armv7-unknown-linux-gnueabihf
      - name: Create Docker Backup
        run: docker save --output docker.tar eigenein/my-iot-rs/arm-unknown-linux-gnueabihf eigenein/my-iot-rs/armv7-unknown-linux-gnueabihf

      - name: Release
        id: release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload for Raspberry Pi 0/1
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/arm-unknown-linux-gnueabihf/release/my-iot
          asset_name: my-iot-arm-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream

      - name: Upload for Raspberry Pi 2/3/4
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/armv7-unknown-linux-gnueabihf/release/my-iot
          asset_name: my-iot-armv7-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream
