name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create a GitHub Release
        id: release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Install Cross
        run: cargo install cross  # we need OpenSSL from SQLx #515 #575

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build for Raspberry Pi 0/1
        run: cross build --target arm-unknown-linux-gnueabihf
      - name: Build for Raspberry Pi 2/3/4
        run: cross build --target armv7-unknown-linux-gnueabihf

      - name: Upload for arm-unknown-linux-gnueabihf
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/arm-unknown-linux-gnueabihf/release/my-iot
          asset_name: my-iot.arm-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream

      - name: Upload for armv7-unknown-linux-gnueabihf
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: target/armv7-unknown-linux-gnueabihf/release/my-iot
          asset_name: my-iot.armv7-unknown-linux-gnueabihf
          asset_content_type: application/octet-stream
